### ISSUE TITLE
Documentation is not findable using Google

### ISSUE THREAD

**Issue by newz2000** [balderdashy/www.sailsjs.org#50]
Do this:

Google Search For:

* Sails.js testing

Expected result:

* First link is to the [documentation for testing](http://sailsjs.org/#/documentation/concepts/Testing), or at least
 * One of the first few links is to the official documentation

Actual result:

* Of the first 10 results on Google none take you to the proper page. Two of the links (numbers 5 and 6) take you to the sails.js website, but not the correct page.

Do this:

Search just the sails.js site for information about testing using this search:

site:sailsjs.org testing

Expected result:

* First link is to the [documentation for testing](http://sailsjs.org/#/documentation/concepts/Testing)

Actual result:

* The proper link did not show up in the results at all - there were only 10 results returned from Google and none of them take you to the proper page.

The impact of this is that people who are looking for help using Sails.js usually don't immediately find their way to the source of the most up to date and relevant information on the product.

**Comment by mikermcneil** [comment]
@newz2000 very awesome, I appreciate your help. cc https://github.com/balderdashy/sails/issues/2594

**Comment by rachaelshaw** [comment]
The docs pages seem to be indexed correctly for the most part, now that we've updated the site to not use angular routes. And old links should redirect to the right place for the most part, so I'm going to call this one good.

**Comment by mikermcneil** [comment]
Huge thanks to @rachaelshaw for her help completely re-architecting the Sails website for better SEO.
