### ISSUE TITLE
the back button is broken

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/www.sailsjs.org#55]
go here: http://sailsjs.org/#/documentation/concepts/extending-sails/Hooks

click on any of the links, then try to click the Back or cmd+left arrow. it does not work

**Comment by kevinburkeshyp** [comment]
most of the links on that page are also broken

**Comment by mikermcneil** [comment]
@kevinburkeshyp thanks!  Fixed by @sgress454 in https://github.com/balderdashy/www.sailsjs.org/commit/23d14d8b67b5abd1cf44814b7b258c4da75e2adf
