### ISSUE TITLE
TODOs displayed on Get Started page

### ISSUE THREAD

**Issue by vire** [balderdashy/www.sailsjs.org#59]
Is it intended to display TODOs on the sails main page?
Loose Coupling and Pragmatism on the http://sailsjs.org/#!/getStarted page

also this those section links aren't working as well

http://sailsjs.org/#!/getStarted?q=loose-coupling 
http://sailsjs.org/#!/getStarted?q=pragmatism

**Comment by rachaelshaw** [comment]
Looks like this was fixed at some point
