### ISSUE TITLE
Is something missing?  Flashes briefly before content loads on each page.

### ISSUE THREAD

**Issue by sgress454** [balderdashy/www.sailsjs.org#60]
From: https://github.com/balderdashy/sails-docs/issues/395

When you click any link, this text appears before the content loads:
>Is something missing?
If you notice something we've missed or could be improved on, please follow this link and submit a pull request to the sails-docs repo. Once we merge it, the changes will be immediately reflected on the website.

It is pushed to the bottom of the page when the content finally renders, but for a second it looks like a 404.  Need to put a loading message in there instead.

**Comment by rachaelshaw** [comment]
I think this can be closed now we've redone the documentation pages; let me know if you see this again.
