### ISSUE TITLE
[proposal] Links in sails-docs and www.sailsjs.org

### ISSUE THREAD

**Issue by jub3i** [balderdashy/www.sailsjs.org#66]
The links situation at balderdashy/sails-docs is a wee bit of a mess! In the docs all the links are hard coded to the sails website (hashbangs and what not included). I think a nice clean solution would be to use relative links in the docs, so that the docs can stand on their own and be a proper independent repo. Then the website can interpret those relative links and prepend hashbangs and whatever angular black magic you guys want. 

I've been wanting to really polish the docs and the whole link situation is a big stumbling block to accomplish that. I'm not sure how much work my proposal would cause for this repo, as I'm not familiar with Angular, but do you think writing some logic for interpreting relative url's is a ton of work?

Would love to know what you think. @rachaelshaw  @mikermcneil

**Comment by sgress454** [comment]
This has always been the dream, that the links on the repo would link to other repo pages, and magically be interpreted on the website to be links to sailsjs.org pages.  It probably even worked at some point.  Right now @phishy is working with us to move the site into a more sustainable place, so I don't know that now is the time to go and scrub all the links--or maybe it's the perfect time...

**Comment by jub3i** [comment]
@sgress454 I share this dream :) There seems to be at least 1 or 2 issues or PR's on sails-docs every week regarding links, its getting old really really fast! :) No better time than now IMHO! After this site pulls down the sails-docs repo to disk, it would have to parse the .md files for relative links and update them with the hashbang magic stuff - I have to idea really, but doesn't sound too difficult? (I guess that would be one way of doing it)

Perhaps forking the sails-docs repo now and have the site rely on the fork - while we immediately move forward on master branch and assimilate the many 'links related' PR and issues and bring it to a place where it is its own independent repo right away?

**Comment by mikermcneil** [comment]
@jub3i Are you committed to taking lead on this?  If so, I'm down, and really appreciate the help :)

**Comment by jub3i** [comment]
@mikermcneil What exactly do you mean when you say "take the lead on this"? I'd be happy to bring the docs into a state that it can be considered an independent repo. Do you mean make the site work too? I'm not opposed to doing both, but I'd like to be clear about what it is, you would be comfortable, I work on. I don't want to do a bunch of work on the site and then have it not merged because someone else is working on something different or has other plans. 

@phishy apparently you are working on the site? Do you have any thoughts?

**Comment by phishy** [comment]
@jub3i I'm waiting for a contract to finish up, and then I'm going to work on turning the www.sailsjs.org repo into a static site. If you want to talk it out and work together, that would be pretty awesome.

**Comment by jub3i** [comment]
@mikermcneil @sgress454 Ok phishy and I have gotten in touch and plan to move on this. Roughly our plans are: 

**balderdashy/www.sailsjs.org**
- remove angular from www.sailsjs.org, have it work off .md files
- keep the current style
- have a simple menu for docs based off the structure of balderdashy/sails-docs repo
 - we may iterate on the docs portion of balderdashy/www.sailsjs.org after we have integrated the planned changes to sails-docs; perhaps a nicer menu and/or have a quick search feature
- add in a step after doc-templater to convert relative links for docs, or something like that.

**balderdashy/sails-docs**
- make all links be relative, so it can be its own independent repo

@phishy Let me know if I left anything out :)

**Comment by kevinburkeshyp** [comment]
static site sounds great - would just hope that you are planning to preserve redirects so content that exists (or previously existed) doesn't 404.

**Comment by rachaelshaw** [comment]
Closing this, because the link situation is looking a lot better now, but it would still be nice to look into the relative link thing in the future. (They won't work right away at the moment, since the links on the website don't completely match up with the paths in the documentation repo.)
