### ISSUE TITLE
back button is broken again

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/www.sailsjs.org#68]
Steps to reproduce:

1. search Google for "sails adapters"

2. click on the third result, "Custom Adapters"

3. get shown a generic page that doesn't contain any information on custom adapters

4. click the Back button to try another page in Google. You can't navigate backwards to Google.

**Comment by sgress454** [comment]
Works for me.  What browser are you using?

**Comment by kevinburkeshyp** [comment]
I was able to reproduce it on both Chrome and Firefox.

**Comment by kevinburkeshyp** [comment]
When you click the Back arrow URL tab flashes http://sailsjs.org/#!/documentation/custom-adapters, which is then re-redirected to http://sailsjs.org/#!/documentation/concepts. I can take a video if you like. I just reproduced it again in an incognito window.

**Comment by sgress454** [comment]
I believe you, I just can't reproduce using your steps in either of those browsers, in regular or incognito windows.  @rachaelshaw @mikermcneil @particlebanana anybody else seeing this?

**Comment by kevinburkeshyp** [comment]
If it makes any difference, I'm on a Mac, running Chrome 42.0.2311.90.

**Comment by dudemelo** [comment]
Works for me. The "redirection" is dynamic, i have no idea of what may be occurring.

**Comment by tjwebb** [comment]
I don't have any back button issue, but clicking on stuff from Google that links to sailsjs.org always just takes me to the main sailsjs.org page. The links to the individual documentation pages don't seem to work at all.

**Comment by tjwebb** [comment]
For starters, Google has the URL wrong. It should link to: http://sailsjs.org/#!/documentation/concepts/extending-sails/Adapters. How can we fix this?

**Comment by kevinburkeshyp** [comment]
Probably the best way would be to check the access logs, if you get the query after the fragment, if you don't have that, check out the repo from 8 months ago, and set up redirects from the old routes to the new pages. 

Failing that, you can probably submit a sitemap to Google, and they might even have tools that let you submit redirects from the old routes to the new.

Given traffic will still come in on the old routes (via, among other things, the ~60K auto-generated links at the top of Sails model files), you probably want to set up redirects.

**Comment by rachaelshaw** [comment]
This should be okay now, since we aren't using frontend routes anymore and Google seems to have indexed most of the new ones at this point.

Re: old routes, those should redirect to the right place for the most part.
