### ISSUE TITLE
[Bug] Link about agnostic frontend is broken

### ISSUE THREAD

**Issue by fernandoguedes** [balderdashy/www.sailsjs.org#78]
Hey guys, 

I'm was reading Sails Documentation and check the http://sailsjs.org/features#?front-end, but this link is broken.

Regards.

**Comment by sgress454** [comment]
Hm, works for me™.  It just scrolls down to the "Front-end agnostic" section on that page anyway.  What browser are you using?

**Comment by fernandoguedes** [comment]
I'm using Firefox. I suspect that the link is private.

**Comment by sgress454** [comment]
Works for me on Firefox, too.  Again, it's not really a link, just an anchor that scrolls down to the "Front-end agnostic" section of the same page.  What happens when you click on it?

**Comment by fernandoguedes** [comment]
![403_broken_link](https://cloud.githubusercontent.com/assets/489937/11073984/456e8934-87d4-11e5-8c5d-cde114f8c8b5.png)

**Comment by sgress454** [comment]
Erm, that's definitely not coming from the Sails site.  Maybe there is some extension or plugin at work?  Where do the "sign in", "help center", "forums" and "home" links go to?

**Comment by particlebanana** [comment]
That's the dropbox 403 page. Possibly an extension or something is trying to load something from Dropbox?

**Comment by fernandoguedes** [comment]
@particlebanana and @sgress454, this broken link is about "AGNOSTIC FRONTEND", a reference to Dropbox in SailsJS docs.

![sails_agnostic_1](https://cloud.githubusercontent.com/assets/489937/11117369/5cbd4db2-8920-11e5-9773-3b69806a39bd.png)

![sails_agnostic_2](https://cloud.githubusercontent.com/assets/489937/11117373/61a3e96c-8920-11e5-9f67-7799ab9a38db.png)

**Comment by particlebanana** [comment]
Ah yeah looks like it's a bit.ly link pointing to a private dropbox link. http://bit.ly/be-dev-agnostic @rachaelshaw any ideas what is supposed to be there?

**Comment by rachaelshaw** [comment]
Hmm, it was a link to a slide deck, but I can't find another version of it. Guess I'll just remove it.
