### ISSUE TITLE
Assets compilation failure?

### ISSUE THREAD

**Issue by zeluis9** [balderdashy/www.sailsjs.org#81]
While reading the docs, found this: 

![captura de ecra de 2016-01-26 14 58 58](https://cloud.githubusercontent.com/assets/11177829/12584016/676d872e-c43d-11e5-9c2e-9eaa09b33533.png)

Appears on the first level (http://sailsjs.org/documentation/concepts/:concept)

**Comment by zeluis9** [comment]
![captura de ecra de 2016-01-26 17 34 12](https://cloud.githubusercontent.com/assets/11177829/12588939/0fe375d4-c453-11e5-97d1-39a0e6a8bdf0.png)

**Comment by sgress454** [comment]
Thanks for the report @zeluis9.  We've cleared out some cobwebs and the site should be functioning normally now.
